### ISSUE TITLE
[Vendor app - interface] Adjust all the pictures and make them to be displayed similarly 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#1]
![image](https://cloud.githubusercontent.com/assets/26451941/24088074/5fca5cec-0d50-11e7-9430-f5c3efc60a01.png)
Right now we have our pictures displayed not similarly some pictures are displlayed in bigger sizes and some are not, and we need to display them similarly maybe in a kinda frame.

**Comment by AndroidAkyl** [comment]
![image](https://cloud.githubusercontent.com/assets/26451941/24088132/01c96f10-0d51-11e7-9fd3-a65724f35524.png)
also I think we should add this type of an item by clicking which the whole picture will be zoomed in.

**Comment by hasan5151** [comment]
![screenshot_20170320-105258](https://cloud.githubusercontent.com/assets/17989735/24089035/db234326-0d5b-11e7-8b7f-a9a7bd371fc5.png)
![screenshot_20170320-105300](https://cloud.githubusercontent.com/assets/17989735/24089036/db23d0fc-0d5b-11e7-8ab2-e293fc67c7c1.png)
