### ISSUE TITLE
Notification does not go away even when messages are read (clicked)

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#37]
![img_20170526_152951](https://cloud.githubusercontent.com/assets/26451941/26489191/3746d5ea-4228-11e7-85a3-4843fde94651.png)

**Comment by hasan5151** [comment]
this one is work on my telephone. Can you send me screenshot  inside of Сообщения  ? is there any bold msg ?

**Comment by AndroidAkyl** [comment]
Everything is working fine now , maybe I was testing it when you were merging changes , or working with database ... but now it's working fine.
