### ISSUE TITLE
Unexpected logging out

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#39]
![screenshot_2017-06-06-15-28-59](https://cloud.githubusercontent.com/assets/26451941/26822744/ef36c08c-4acc-11e7-9486-204144d3d1e9.png)

**Comment by AndroidAkyl** [comment]
I am still facing this issue

**Comment by hasan5151** [comment]
just 1 time log in after it will save your email and  password

9 Haz 2017 14:54 tarihinde "AndroidAkyl" <notifications@github.com> yazdı:

**Comment by AndroidAkyl** [comment]
Ok
