### ISSUE TITLE
SubCategory Performans 

### ISSUE THREAD

**Issue by hasan5151** [AndroidAkyl/Vendor-App-#41]
> Hello
> A general guideline is to not use more than 20 tags per user. You can add more but the more you add the slower it will be.
> Also try to use our pre made filters when possible:
> Please see our segments guide: https://documentation.onesignal.com/docs/segmentation
> And our filters section within the guide above: https://documentation.onesignal.com/docs/segmentation#section-filter-types
> Thanks.
> 
this is from our notification server

**Comment by AndroidAkyl** [comment]
So what should we do to use more than 200 categories? Is there a payment option?
