### ISSUE TITLE
Notification number is not working 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#42]

**Comment by AndroidAkyl** [comment]
![img_20170609_122358](https://user-images.githubusercontent.com/26451941/26963498-af23cd7a-4d0e-11e7-8f71-88bf09928bfe.png)
I have no items but I still can see notification

**Comment by hasan5151** [comment]
clear cache it is working

**Comment by AndroidAkyl** [comment]
this cache thing is kinda disturbing, can we not avoid cleanings of cache everytime? 
because if I as a user clean cache then I will have to relogin again, and there is a big chance of me forgotting the password or email...

**Comment by hasan5151** [comment]
this is for 1 time
