### ISSUE TITLE
Segments - One signal 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#46]
How many cars have we segmented into tags already?

**Comment by hasan5151** [comment]
13

**Comment by AndroidAkyl** [comment]
and how many is left? 15?

**Comment by hasan5151** [comment]
yes

9 Haz 2017 15:06 tarihinde "AndroidAkyl" <notifications@github.com> yazdı:

**Comment by hasan5151** [comment]
25

9 Haz 2017 15:06 tarihinde "Huzeyfe AKGÜN" <hasanyildiz5151@gmail.com>
yazdı:

**Comment by AndroidAkyl** [comment]
Please list them here

**Comment by hasan5151** [comment]
"subaru","isuzu","pontiac","hummer","chrysler","chevrolet","ford","jeep","lincoln","dodge","cadillac","mercury","hyundai","daewoo","kia","volvo","skoda","saab","roverx","landrover","porsche","renault","jaguar","opel","lada"

**Comment by AndroidAkyl** [comment]
Thank you

**Comment by AndroidAkyl** [comment]
1. Subaru - done 
2. isuzu - done 
3. pontiac - done
4. hummer - done 
5. chrysler - done 
6. chevrolet - done
7. ford - done 
8. jeep - done 
9.lincoln - done 
10. dodge - done 
11. cadillac - done 
12. mercury - done 
13. hyundai - done 
14. daewoo -  done 
15. kia - done
16. volvo - done
17. skoda - done
18. saab -  done
19. roverx - done 
20. landrover - done 
21. porsche - done 
22. renault - done 
23. jaguar - done 
24. opel - done
25. lada - done
