### ISSUE TITLE
Newer info should be placed first 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#48]
![img_20170609_143815](https://user-images.githubusercontent.com/26451941/26967789-5d8dc69c-4d21-11e7-97e4-f2d58a1acd3a.png)

**Comment by hasan5151** [comment]
[https://stackoverflow.com/questions/27207059/firebase-query-double-nested ](url)

we need to change code for it 

"The Firebase API only allows you to filter children one level deep (or with a known path) with its orderByChild and equalTo methods."
