### ISSUE TITLE
Use a smaller font for the subcategories text

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#57]
![img_20170615_161714](https://user-images.githubusercontent.com/26451941/27176895-39cbf28c-51e6-11e7-929e-b8bf47a8b328.png)
Also buttons now moved and are not placed as they used to.

**Comment by AndroidAkyl** [comment]
Because the font of categories text is big our buttons are relocating, to avoid that we need use smaller font.

**Comment by hasan5151** [comment]
this is bcoz of padding. I used padding for all layout. But we can do categories smaller.
