### ISSUE TITLE
While going through items page reloads and app quits 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#59]
![img_20170615_162848](https://user-images.githubusercontent.com/26451941/27177345-dde3f29c-51e7-11e7-9eea-01e364b2ae98.png)

**Comment by hasan5151** [comment]
did you update the app?

**Comment by AndroidAkyl** [comment]
Yes

**Comment by hasan5151** [comment]
try again

**Comment by AndroidAkyl** [comment]
its fine now, but no items there )))

**Comment by hasan5151** [comment]
bcoz i deleted all db

**Comment by AndroidAkyl** [comment]
so this issues is fixed?

**Comment by hasan5151** [comment]
i think so

**Comment by AndroidAkyl** [comment]
)))
