### ISSUE TITLE
Nulls again 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#60]
![img_20170615_163225](https://user-images.githubusercontent.com/26451941/27177453-468f8aae-51e8-11e7-9e38-be64077e7d91.png)

**Comment by hasan5151** [comment]
i changed db thats why

**Comment by AndroidAkyl** [comment]
ok, but still we should not have it this way.. vendors wont like it

**Comment by hasan5151** [comment]
this is for us :)

**Comment by hasan5151** [comment]
they didnt sell anything yet

**Comment by AndroidAkyl** [comment]
ooh ok ))
