### ISSUE TITLE
Cannot see my offers 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#63]
![img_20170615_175116](https://user-images.githubusercontent.com/26451941/27180090-7b343cd6-51f3-11e7-8bcf-4ba7f4e043fe.png)
When I get into my offers I don't see anything.

**Comment by hasan5151** [comment]
i forgot remove my user id thats why

**Comment by AndroidAkyl** [comment]
Ok)
