### ISSUE TITLE
Categories should memorize its status 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#69]
![screenshot_2017-06-19-14-03-30](https://user-images.githubusercontent.com/26451941/27275236-582bede4-54f8-11e7-80ff-d10ed586d8cd.png)
As Bolot has mentioned, categories should memorize its status, for example:
When user clicks subcategories and chooses nothing that particular category is not enabled, but if user has enabled some subcategories before and just wants to check out subcategories, and enables no subcategories that particular category gets disabled. We need to make it so that app memorizes all the enabled before categories and subcategories.

**Comment by AndroidAkyl** [comment]
@hasan5151 are you already done with this issue? :)

**Comment by hasan5151** [comment]
yes
