### ISSUE TITLE
Change text 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#70]
![img_20170619_153523](https://user-images.githubusercontent.com/26451941/27279017-032d7d78-5505-11e7-834b-094e05e98424.png)
Text needs to be changed to : Bishkek Bid

**Comment by AndroidAkyl** [comment]
I still can see the Autoparts text

**Comment by hasan5151** [comment]
we cant change text bcoz this service closed.

**Comment by AndroidAkyl** [comment]
Ooh ok , then let's close the issue.
