### ISSUE TITLE
Automatically generate new emails 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#79]

**Comment by hasan5151** [comment]
what is this can you explain pls? i didnt understand exactly

**Comment by AndroidAkyl** [comment]
While registering with the vendor app , user has to provide email right? can we get rid off that email for now? if not , we have to autoamitcally generate new emails for users so they wont have to enter emails all the time

**Comment by AndroidAkyl** [comment]
@hasan5151 ???

**Comment by AndroidAkyl** [comment]
Not actual now - closing the issue
