### ISSUE TITLE
Forgot password item and its functionality 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Vendor-App-#9]
We need to add up an item for the login page -where users can get new passwords.

**Comment by hasan5151** [comment]
need to translate

**Comment by hasan5151** [comment]
Reset Your Password
Hello!

It looks like you've forgotten your password.

Use the following temporary password within the next 24 hours to log in and update your account: scnmQYmRF7fFMKjc

Thanks!
